# Generated by Django 5.1.2 on 2024-12-19 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skillSeeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('budget', models.IntegerField()),
                ('deadline', models.DateField()),
                ('requirements', models.TextField(blank=True, null=True)),
                ('anyAttachment', models.FileField(blank=True, null=True, upload_to='projects/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skillSeeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillSeeker.skillseeker')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectcategory')),
            ],
        ),
    ]
