# Generated by Django 5.1.2 on 2024-12-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectcategory_icon_projectcategory_services_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='anyAttachment',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
