# Generated by Django 5.1.2 on 2024-12-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillSeeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillseeker',
            name='company_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='skillseeker',
            name='company_employee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skillseeker',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='skillSeeker/images/company'),
        ),
        migrations.AlterField(
            model_name='skillseeker',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skillseeker',
            name='company_started',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='skillseeker',
            name='company_website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
