# Generated by Django 5.1.2 on 2024-12-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillSeeker', '0002_alter_skillseeker_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillseeker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skillSeeker/images/skillSeeker/'),
        ),
    ]
