# Generated by Django 5.1.2 on 2024-12-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillSeeker', '0003_alter_skillseeker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillseeker',
            name='company_logo',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='skillseeker',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
