# Generated by Django 5.1.2 on 2024-12-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillCrafter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcrafter',
            name='curriculum_vitae',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='skillcrafter',
            name='last_educational_organization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skillcrafter',
            name='last_educational_qualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skillcrafter',
            name='passing_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skillcrafter',
            name='result',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='skillcrafter',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
